# Generated by Django 3.2.11 on 2022-06-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=12)),
                ('year', models.IntegerField(max_length=4)),
                ('vin', models.CharField(max_length=17)),
                ('millas', models.IntegerField()),
                ('categoria', models.IntegerField()),
                ('locacion', models.IntegerField()),
                ('disponibildad', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registrar auto',
                'verbose_name_plural': 'Registrar autos',
            },
        ),
    ]
