# Generated by Django 3.2.11 on 2022-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroauto',
            old_name='disponibildad',
            new_name='disponibilidad',
        ),
        migrations.AlterField(
            model_name='registroauto',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='registroauto',
            name='year',
            field=models.IntegerField(),
        ),
    ]
