# Generated by Django 3.2.11 on 2022-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0003_alter_registroauto_actualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='unirmeRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=12)),
                ('modelo', models.CharField(max_length=12)),
                ('year', models.IntegerField()),
                ('millas', models.IntegerField()),
                ('locacion', models.IntegerField()),
                ('Contactado', models.BooleanField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unirme',
            },
        ),
    ]
