# Generated by Django 3.2.11 on 2022-06-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0004_unirmeregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='unirmeregistro',
            name='email',
            field=models.EmailField(default='n/a', max_length=254),
        ),
        migrations.AddField(
            model_name='unirmeregistro',
            name='telefono',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
