# Generated by Django 3.2.11 on 2022-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0005_auto_20220604_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unirmeregistro',
            options={},
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='locacion',
            field=models.IntegerField(choices=[('guayaquil', 'Guayaquil'), ('quito', 'Quito'), ('cuenca', 'Cuenca')]),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='millas',
            field=models.IntegerField(choices=[('0-15000', '0-15000 km'), ('15-50000', '15-50000 km'), ('50-100000', '50-100000 km'), ('100-150000', '100-150000 km'), ('+150000', '+150000 km')]),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)]),
        ),
    ]
