# Generated by Django 3.2.11 on 2022-06-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0006_auto_20220604_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unirmeregistro',
            name='Contactado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='locacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='millas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='year',
            field=models.IntegerField(),
        ),
    ]
