# Generated by Django 3.2.11 on 2022-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0007_auto_20220604_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unirmeregistro',
            name='millas',
            field=models.CharField(choices=[('0-15000', '0-15000 km'), ('15-50000', '15-50000 km'), ('50-100000', '50-100000 km'), ('100-150000', '100-150000 km'), ('+150000', '+150000 km')], max_length=20),
        ),
    ]
