# Generated by Django 3.2.11 on 2022-06-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0010_auto_20220605_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unirmeregistro',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='locacion',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='millas',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='year',
            field=models.IntegerField(),
        ),
    ]
