# Generated by Django 3.2.11 on 2022-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0012_unirmeregistro_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unirmeregistro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
