# Generated by Django 3.2.11 on 2022-06-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0013_alter_unirmeregistro_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='unirmeregistro',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
