# Generated by Django 3.2.11 on 2022-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_auto', '0014_unirmeregistro_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unirmeregistro',
            name='Contactado',
        ),
        migrations.AddField(
            model_name='unirmeregistro',
            name='estado',
            field=models.CharField(choices=[('contactado', 'Contactado'), ('registroauto', 'Registro auto'), ('noInteresado', 'No esta interesado')], default='n/a', max_length=30),
        ),
        migrations.AlterField(
            model_name='unirmeregistro',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
